name: transit-env
dependencies:
- openssl=1.0.2e=0
- pip=7.1.2=py27_0
- python=2.7.11=0
- readline=6.2=2
- setuptools=19.1.1=py27_0
- sqlite=3.9.2=0
- tk=8.5.18=0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- pip:
  - appnope==0.1.0
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.5.0.1
  - certifi==2015.11.20.1
  - decorator==4.0.6
  - functools32==3.2.3.post2
  - gnureadline==6.3.3
  - gtfs-realtime-bindings==0.0.4
  - ipykernel==4.2.2
  - ipython==4.0.1
  - ipython-genutils==0.1.0
  - ipywidgets==4.1.1
  - jinja2==2.8
  - jsonschema==2.5.1
  - jupyter==1.0.0
  - jupyter-client==4.1.1
  - jupyter-console==4.0.3
  - jupyter-core==4.0.6
  - markupsafe==0.23
  - mistune==0.7.1
  - nbconvert==4.1.0
  - nbformat==4.0.1
  - notebook==4.1.0
  - path.py==8.1.2
  - pexpect==4.0.1
  - pickleshare==0.5
  - protobuf==2.6.1
  - ptyprocess==0.5
  - pygments==2.0.2
  - pyzmq==15.2.0
  - qtconsole==4.1.1
  - simplegeneric==0.8.1
  - singledispatch==3.4.0.3
  - six==1.10.0
  - terminado==0.6
  - tornado==4.3
  - traitlets==4.0.0

